language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

before_script:
  - composer install --prefer-dist --dev

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -p src/ tests/

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true
